/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { Outlines, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Flavor_Yuzu: THREE.Mesh;
  };
  materials: {};
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("./3D/Flavor_Lychee.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Flavor_Yuzu.geometry}
        material={nodes.Flavor_Yuzu.material}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshPhysicalMaterial
          color={"#FFFFFF"}
          opacity={9}
          transmission={0.6}
          thickness={0.8}
          ior={1}
          roughness={0.2}
          clearcoat={0.6}
        />
        <Outlines thickness={0.1} color={"#F8F8F8"} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/Flavor_Lychee.glb");
