/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { Outlines, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Regular_ice: THREE.Mesh;
  };
  materials: {};
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("./3D/Regular_Ice.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Regular_ice.geometry}
        material={nodes.Regular_ice.material}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshPhysicalMaterial
          // clearcoat={0.6}
          color={"#1e90ff"}
          roughness={0.2}
        />
        <Outlines thickness={0.1} color={"#DBF1FD"} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/Regular_Ice.glb");
