/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { GradientTexture, Outlines, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Milk: THREE.Mesh;
  };
  materials: {};
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("./3D/Milk.glb") as GLTFResult;
  return (
    <group {...props} dispose={null} renderOrder={0}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Milk.geometry}
        material={nodes.Milk.material}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshPhysicalMaterial
          color={"#FDF4DC"}
          opacity={9}
          transmission={0.6}
          thickness={0.8}
          ior={1}
          roughness={0.2}
          clearcoat={0.6}
        />
        <Outlines thickness={0.1} color={"#EFE7DF"} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/Milk.glb");
