/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mini_Mochi: THREE.Mesh;
  };
  materials: {
    lambert8SG: THREE.MeshPhysicalMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("./3D/Mini_Mochi.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mini_Mochi.geometry}
        material={materials.lambert8SG}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshPhysicalMaterial color={"white"} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/Mini_Mochi.glb");
