/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { MeshPhongMaterial, MeshPhysicalMaterial } from "three";

type GLTFResult = GLTF & {
  nodes: {
    Star_Boba: THREE.Mesh;
  };
  materials: {};
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("./3D/Star_Boba.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Star_Boba.geometry}
        material={nodes.Star_Boba.material}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshPhysicalMaterial color={"yellow"} roughness={0.4} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/Star_Boba.glb");
