/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Suagr_Regular: THREE.Mesh;
  };
  materials: {};
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("./3D/Suagr_Regular.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Suagr_Regular.geometry}
        material={nodes.Suagr_Regular.material}
        rotation={[Math.PI / 2, 0, 0]}
      >
        {" "}
        <meshPhysicalMaterial
          color={"white"}
          roughness={0.1}
          thickness={0.2}
          ior={9}
          clearcoat={0.2}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/Suagr_Regular.glb");
