/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Boba: THREE.Mesh;
  };
  materials: {};
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/3D/boba.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Boba.geometry} rotation={[Math.PI / 2, 0, 0]}>
        <meshLambertMaterial color="black" />
      </mesh>
    </group>
  );
}

useGLTF.preload("/boba.glb");
